//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationAnywhere.MetaBot.SharePoint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource4Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource4Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharepointAPI.Test.Resource4Test", typeof(Resource4Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\workspace\MetabotTest\sample.txt.
        /// </summary>
        internal static string localFile {
            get {
                return ResourceManager.GetString("localFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\workspace\MetabotTest.
        /// </summary>
        internal static string localFolder {
            get {
                return ResourceManager.GetString("localFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/SolutionArchitectTeam/Shared Documents/General/Working_Files_Naoya/MetabotTest/origin/sample.txt.
        /// </summary>
        internal static string remoteFilePath {
            get {
                return ResourceManager.GetString("remoteFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/SolutionArchitectTeam/Shared Documents/General/Working_Files_Naoya/MetabotTest/origin.
        /// </summary>
        internal static string remoteFolderPath {
            get {
                return ResourceManager.GetString("remoteFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/SolutionArchitectTeam/Shared Documents/General/Working_Files_Naoya/MetabotTest/target/sample.txt.
        /// </summary>
        internal static string remoteWorkFilePath {
            get {
                return ResourceManager.GetString("remoteWorkFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/SolutionArchitectTeam/Shared Documents/General/Working_Files_Naoya/MetabotTest/target.
        /// </summary>
        internal static string remoteWorkFolderPath {
            get {
                return ResourceManager.GetString("remoteWorkFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Architect Team.
        /// </summary>
        internal static string siteName {
            get {
                return ResourceManager.GetString("siteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://automationanywhere1.sharepoint.com/sites/SolutionArchitectTeam/.
        /// </summary>
        internal static string siteURL {
            get {
                return ResourceManager.GetString("siteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naoya.murao@automationanywhere.com.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
